import Loglib from "@loglib/tracker/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Loglib
          config={{
            id: "analytics_antonin",
            host: "https://www.loglib.io",
          }}
        />
      </body>
    </html>
  );
}
